package services

var countryNames = map[string]string{
	"NG": "Nigeria",
	"BJ": "Benin",
	"TZ": "Tanzania",
	"UG": "Uganda",
	"KE": "Kenya",
	"GH": "Ghana",
	"ZA": "South Africa",
	"ML": "Mali",
	"SN": "Senegal",
	"ET": "Ethiopia",
	"CM": "Cameroon",
	"CD": "DR Congo",
	"MW": "Malawi",
	"ZW": "Zimbabwe",
	"MZ": "Mozambique",
	"RW": "Rwanda",
	"EG": "Egypt",
	"TN": "Tunisia",
	"DZ": "Algeria",
	"MA": "Morocco",
	"SD": "Sudan",
	"ER": "Eritrea",
	"BF": "Burkina Faso",
	"CI": "Côte d'Ivoire",
	"LR": "Liberia",
	"SL": "Sierra Leone",
	"GM": "Gambia",
	"GN": "Guinea",
	"GW": "Guinea-Bissau",
	"TG": "Togo",
	"GA": "Gabon",
	"CG": "Republic of the Congo",
	"AO": "Angola",
	"ZM": "Zambia",
	"NA": "Namibia",
	"BW": "Botswana",
	"SZ": "Eswatini",
	"LS": "Lesotho",
	"MU": "Mauritius",
	"MR": "Mauritania",
	"NE": "Niger",
	"TD": "Chad",
	"CF": "Central African Republic",
	"DJ": "Djibouti",
	"SO": "Somalia",
	"BI": "Burundi",
	"MG": "Madagascar",
	"CV": "Cape Verde",
	"LY": "Libya",
	"SY": "Syria",
	"LB": "Lebanon",
	"IL": "Israel",
	"JO": "Jordan",
	"IQ": "Iraq",
	"KW": "Kuwait",
	"SA": "Saudi Arabia",
	"AE": "United Arab Emirates",
	"QA": "Qatar",
	"BH": "Bahrain",
	"OM": "Oman",
	"IR": "Iran",
	"AF": "Afghanistan",
	"PK": "Pakistan",
	"IN": "India",
	"BD": "Bangladesh",
	"MM": "Myanmar",
	"TH": "Thailand",
	"LA": "Laos",
	"VN": "Vietnam",
	"CN": "China",
	"KP": "North Korea",
	"KR": "South Korea",
	"JP": "Japan",
	"PH": "Philippines",
	"MY": "Malaysia",
	"ID": "Indonesia",
	"SG": "Singapore",
	"BN": "Brunei",
	"US": "United States",
	"CA": "Canada",
	"MX": "Mexico",
	"GT": "Guatemala",
	"CU": "Cuba",
	"JM": "Jamaica",
	"HT": "Haiti",
	"DO": "Dominican Republic",
	"PR": "Puerto Rico",
	"CR": "Costa Rica",
	"PA": "Panama",
	"HN": "Honduras",
	"SV": "El Salvador",
	"NI": "Nicaragua",
	"BZ": "Belize",
	"CO": "Colombia",
	"VE": "Venezuela",
	"EC": "Ecuador",
	"PE": "Peru",
	"BO": "Bolivia",
	"PY": "Paraguay",
	"UY": "Uruguay",
	"AR": "Argentina",
	"BR": "Brazil",
	"CL": "Chile",
	"GB": "United Kingdom",
	"FR": "France",
	"DE": "Germany",
	"IT": "Italy",
	"ES": "Spain",
	"PT": "Portugal",
	"NL": "Netherlands",
	"BE": "Belgium",
	"CH": "Switzerland",
	"AT": "Austria",
	"SE": "Sweden",
	"NO": "Norway",
	"DK": "Denmark",
	"FI": "Finland",
	"IE": "Ireland",
	"IS": "Iceland",
	"GR": "Greece",
	"PL": "Poland",
	"RU": "Russia",
	"UA": "Ukraine",
	"TR": "Turkey",
	"RO": "Romania",
	"HU": "Hungary",
	"CZ": "Czech Republic",
	"AU": "Australia",
	"NZ": "New Zealand",
	"FJ": "Fiji",
	"PG": "Papua New Guinea",
	"SB": "Solomon Islands",
	"WS": "Samoa",
	"TO": "Tonga",
	"VU": "Vanuatu",
}

func getCountryName(code string) string {
	if name, ok := countryNames[code]; ok {
		return name
	}
	return code
}